
# NGRC Code written as a class - adapted from original NGRC paper's codes at https://github.com/quantinfo/ng-rc-paper-code

import numpy as np
from itertools import combinations_with_replacement
from math import comb


class NGRC:
    
    """
    Next-generation reservoir computing (NGRC) object
    
    Attributes
    ----------
    ndelay : int
        Numer of delay terms to use
    deg : int
        Degree of monomials chosen
    reg : float
        Regularisation used for Tikhonov least squares regression
    washout : int
        Amount of washout to use during training. 
        Code automatically takes the delay terms from the delay-th term in the input onwards. So washout can be 0. 
    isPathContinue : bool, optional
        If the current task is to PathContinue or Forecast. Default: True. 
        
    Methods
    -------
    Train(training_input, training_teacher)
        Performs training using the training input against the training teacher in the NGRC method
    PathContinue(latest_input, nhorizon)
        Simulates forward in time using the latest input for nhorizon period of time
    """

    
    def __init__(self, ndelay, deg, reg, washout, isPathContinue=True):
        
        # Instance attributes that are user defined
        self.ndelay = ndelay                  # Number of delay terms to use         
        self.deg = deg                        # Degree of monomials chosen 
        self.reg = reg                        # Regularisation for least squares Tikhonov
        self.washout = washout                # Washout for training data
        self.isPathContinue = isPathContinue  # Whether is performing path continuing. Affects regression solution. 
        
        # Instance attributes storing arrays generated by methods
        self.Xtrain = None                    # Store for linear feature vectors seen during training
        self.Otrain = None                    # Store for all feature vectors seen during training
        self.Wout = None                      # Weights computed from regression
        
        # Instance attributes storing data dependent values generated by methods
        self.ninputs = None                   # Training size derived from length of data seen during training (input size+1)
        self.nhorizon = None                  # Stores the forecasting horizon given 
        self.ndim = None                      # Stores the number of dimensions given into the system  
        self.ntargets = None                  # Stores the number of target outputs in forecasting
        self.dlin = None                      # Stores the number of NGRC linear features (including delays)
        self.dnonlin = None                   # Stores the number of NGRC nonlinear features 
        self.dtot = None                      # Stores the number of NGRC total features
        
            
    def Train(self, training_input, training_teacher):
        
        """
        Performs training using the training input against the training teacher in the NGRC method
        
        Parameters
        ----------
        training_input : array_like
            Training input for training in NGRC. Must have format (nsamples, ndim)
        training_teacher : array_like
            Training teacher for training in NGRC. Must have format (nsamples, ndim)

        Returns
        -------
        NGRC : class_instance
            NGRC object with training attributes initialised
        """
        
        # Define size and dimension of training data
        self.ninputs = training_input.shape[0] 
        # Define dimension of input based on training data
        self.ndim = training_input.shape[1]
        
        # Assign training teacher instance attributes
        self.ntargets = training_teacher.shape[1]
        
        # Size of linear part of feature vector
        self.dlin = self.ndelay * self.ndim
        
        # Size of nonlinear part of feature vector
        self.dnonlin = 0
        for inter_deg in range(2, self.deg+1):
            self.dnonlin = self.dnonlin + comb(inter_deg+self.dlin-1, self.dlin-1)
        
        # Total size of feature vector: constant + linear + nonlinear
        self.dtot = 1 + self.dlin + self.dnonlin
            
        # Create array to hold linear part of feature vector
        Xtrain = np.zeros((self.dlin, self.ninputs))
        
        # Fill in the linear part of the feature vector
        for delay in range(self.ndelay):
            for j in range(delay, self.ninputs):
                Xtrain[self.ndim*delay:self.ndim*(delay+1), j] = training_input[j-delay, :]
        
        # Create feature vector over training time
        Otrain = np.ones((self.dtot, self.ninputs-self.washout))
        
        # Copy over linear part (shifting by one to account for constant)
        Otrain[1:self.dlin+1, :] = Xtrain[:, self.washout:self.ninputs]
        
        # Fill in nonlinear part of the feature vector
        Orow = 1 + self.dlin
        # Iterate through each monomial degree
        for inter_deg in range(2, self.deg+1):
            # Generate iterator of combinations rows of X for each degree
            iter_monomials = combinations_with_replacement(range(self.dlin), inter_deg)
            # Fill up the rows of O train for each monomial 
            for X_row_ids in iter_monomials:
                monomial_row = Xtrain[X_row_ids[0], self.washout:self.ninputs]
                for row_id in range(1, inter_deg):
                    monomial_row = monomial_row * Xtrain[X_row_ids[row_id], self.washout:self.ninputs]
                Otrain[Orow] = monomial_row
                Orow = Orow + 1
        
        # Assign as instance attributes the linear and nonlinear feature vectors
        self.Xtrain = Xtrain
        self.Otrain = Otrain
         
        # Ridge regression
        if self.isPathContinue == False:
            self.Wout = ((training_teacher[self.washout:]).T @ Otrain.T @ np.linalg.pinv(Otrain @ Otrain.T + self.reg * np.identity(self.dtot))).T
        if self.isPathContinue == True:
            self.Wout = ((training_teacher[self.washout:] - training_input[self.washout:]).T @ Otrain.T @ np.linalg.pinv(Otrain @ Otrain.T + self.reg * np.identity(self.dtot))).T
        
        return self
    
    
    def Forecast(self, testing_input):
        
        # Check and inform user if the wrong task was used in training
        if self.isPathContinue == True:
            raise UserWarning("isPathContinue is True but Forecast is being used. Means training weights might not match the task.")
        
        # Assign testing input instance attributes
        self.nhorizon = testing_input.shape[0]
        
        # Initialise store for the forecast output
        output = np.zeros((self.nhorizon, self.ntargets))
        
        # Create store for feature vectors for prediction
        Otest = np.ones(self.dtot)                        # full feature vector
        Xtest = np.zeros((self.dlin, self.nhorizon+1))    # linear portion of feature vector
        
        # Fill in linear part of feature vector using testing_input
        Xtest[0:self.ndim, 0] = testing_input[0]
        Xtest[self.ndim: , 0] = self.Xtrain[0:self.dlin-self.ndim, -1]
        for j in range(1, self.nhorizon):
            Xtest[0:self.ndim, j] = testing_input[j]
            Xtest[self.ndim: , j] = Xtest[0:self.dlin-self.ndim, j-1]
            
        # Apply Wout to feature vectors to perform prediction
        for j in range(self.nhorizon):
            # Copy linear part into whole feature vector
            Otest[1:self.dlin+1] = Xtest[:, j]  # shift by one for constant
        
            # Fill in the nonlinear part
            Orow = 1 + self.dlin
            # Iterate through each monomial degree
            for inter_deg in range(2, self.deg+1):
                # Generate iterator of combinations rows of X for each degree
                iter_monomials = combinations_with_replacement(range(self.dlin), inter_deg)
                # Fill up the rows of O test for each monomial 
                for X_row_ids in iter_monomials:
                    monomial_row = Xtest[X_row_ids[0], j]
                    for row_id in range(1, inter_deg):
                        monomial_row = monomial_row * Xtest[X_row_ids[row_id], j]
                    Otest[Orow] = monomial_row
                    Orow = Orow + 1
            
            # Perform a prediction
            output[j, :] = Otest @ self.Wout
        
        return output
        
    
    def PathContinue(self, latest_input, nhorizon):
        
        """
        Simulates forward in time using the latest input for nhorizon period of time
        
        Parameters
        ----------
        latest_input : array_like
            Starting input to path continue from
        nhorizon : int
            Period of time to path continue over

        Returns
        -------
        output : array_like
            Output of forecasting
        """
        
        # Check and inform user if the wrong task was used in training
        if self.isPathContinue == False:
            raise UserWarning("isPathContinue is False but PathContinue is being used. Means training weights might not match the task.")
        
        # Assign as instance attributes the testing horizon given
        self.nhorizon = nhorizon
        
        # Create store for feature vectors for prediction
        Otest = np.ones(self.dtot)                        # full feature vector
        Xtest = np.zeros((self.dlin, self.nhorizon+1))    # linear portion of feature vector
        
        # Fill in the linear part of the feature vector with the latest input data and delay
        Xtest[0:self.ndim, 0] = latest_input
        Xtest[self.ndim: , 0] = self.Xtrain[0:self.dlin-self.ndim, -1]
        
        # Apply Wout to feature vector to perform prediction
        for j in range(self.nhorizon):
            # Copy linear part into whole feature vector
            Otest[1:self.dlin+1] = Xtest[:, j] # shift by one for constant
        
            # Fill in the nonlinear part
            Orow = 1 + self.dlin
            # Iterate through each monomial degree
            for inter_deg in range(2, self.deg+1):
                # Generate iterator of combinations rows of X for each degree
                iter_monomials = combinations_with_replacement(range(self.dlin), inter_deg)
                # Fill up the rows of O test for each monomial 
                for X_row_ids in iter_monomials:
                    monomial_row = Xtest[X_row_ids[0], j]
                    for row_id in range(1, inter_deg):
                        monomial_row = monomial_row * Xtest[X_row_ids[row_id], j]
                    Otest[Orow] = monomial_row
                    Orow = Orow + 1

            # Fill in the delay taps of the next state
            Xtest[self.ndim:self.dlin, j+1] = Xtest[0:self.dlin-self.ndim, j]
            # Perform a prediction
            Xtest[0:self.ndim, j+1] = Xtest[0:self.ndim, j] + Otest @ self.Wout
            
        # Store the forecasts as output
        output = Xtest[0:self.ndim, 1:].T
        
        return output
    
    
